### login
POST http://localhost:8002/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

> {%  client.global.set("authToken", response.body.token) %}

### book api
GET http://localhost:8002/books/1
Authorization: Bearer {{authToken}}

### book api with origin
GET http://localhost:8002/books/2
Authorization: Bearer {{authToken}}
Access-Control-Request-Method: GET
Origin: https://example2.com

### paymenet api
GET http://localhost:8002/payments/1
Authorization: Bearer {{authToken}}

### admin api
GET http://localhost:8081/admin
Authorization: Bearer {{authToken}}