spring:
  application:
    name: rag

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true