spring:
  application:
    name: chat-application

  # PostgreSQL 데이터베이스
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:chatdb}?autoCommit=false
    username: ${DB_USERNAME:chatuser}
    password: ${DB_PASSWORD:chatpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      auto-commit: false

    # JPA 설정 (성능 최적화)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 5
        shutdown-timeout: 100ms

    # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 300
      min-spare: 20
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100

# 로깅 설정
logging:
  level:
    com.chat: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: INFO
  pattern:
    console: "[%d{HH:mm:ss}] [${HOSTNAME:unknown}] %-5level %logger{36} - %msg%n"

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        max-age: 3600
  endpoint:
    health:
      show-details: always

# 커스텀 설정 @Value
chat:
  message:
    sequence:
      ttl-hours: 24
    pagination:
      max-limit: 100
      default-limit: 50
  cache:
    default-ttl: 30m
    users-ttl: 1h
    messages-ttl: 5m