spring:
  application:
    name: sql

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
