### 주문 생성
POST {{host}}/orders
Content-Type: application/json

{
  "orderItems": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}

### 주문 결제
POST {{host}}/orders/place
Content-Type: application/json

{
  "orderId": 1
}