### Create Order
POST {{order-server}}/orders
Content-Type: application/json

{
  "items": [
    {
      "productid": 1,
      "quantity": 1
    }
  ]
}

### Place Order
POST {{order-server}}/orders/place
Content-Type: application/json

{
  "orderId": 1
}