### buy
POST {{product-server}}/products/buy
Content-Type: application/json

{
  "requestId": "1",
  "productInfos": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}