### Try
POST {{point-server}}/points/reserve
Content-Type: application/json

{
  "requestId": "1",
  "userId": 1,
  "reserveAmount": 50
}

### Confirm
POST {{point-server}}/points/confirm
Content-Type: application/json

{
  "requestId": "1"
}