/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        double[] values = {1.2, 2.4, 3.6, 4.8, 6.0};

        DescriptiveStatistics stats = new DescriptiveStatistics();

        for (double value: values) {
            stats.addValue(value);
        }

        double mean = stats.getMean();
        double variance = stats.getVariance();

        System.out.println("Mean: " + mean);
        System.out.println("Variance: " + variance);
    }
}
