### 이슈 등록
POST http://localhost:8080/api/v1/issues
Content-Type: application/json

{
  "summary": "테스트",
  "description": "테스트 내용",
  "type": "TASK",
  "priority": "LOW",
  "status": "TODO"
}

### 이슈 목록 조회
GET http://localhost:8080/api/v1/issues

### 이슈 상세 조회
GET http://localhost:8080/api/v1/issues/1

### 이슈 수정
PUT http://localhost:8080/api/v1/issues/1
Content-Type: application/json

{
  "summary": "테스트 수정",
  "description": "테스트 내용 수정",
  "type": "TASK",
  "priority": "HIGH",
  "status": "IN_PROGRESS"
}

### 이슈 삭제
DELETE http://localhost:8080/api/v1/issues/1

### 댓글 등록
POST http://localhost:8080/api/v1/issues/1/comments
Content-Type: application/json

{
  "body": "댓글 입니다."
}