### 회원가입
POST http://localhost:9090/api/v1/users/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234",
  "username": "user"
}

### 로그인
POST http://localhost:9090/api/v1/users/signin
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234"
}

> {% client.global.set("authToken", response.body.token); %}

### 로그아웃
DELETE http://localhost:9090/api/v1/users/logout
Authorization: Bearer {{authToken}}

### 내정보 조회
GET http://localhost:9090/api/v1/users/me
Authorization: Bearer {{authToken}}