spring:
  application:
    name: math

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

upload:
  path: math/src/main/resources/static/uploads/

youtube:
  api-url: https://www.googleapis.com/youtube/v3/search
  api-key: ${YOUTUBE_API_KEY}