### 대기열 등록
POST http://localhost:9010/api/v1/queue?user_id=230

### 진입 허용
POST http://localhost:9010/api/v1/queue/allow?count=1

### 진입 가능 여부 조회
GET http://localhost:9010/api/v1/queue/allowed?user_id=230

### 대기 순번 조회
GET http://localhost:9010/api/v1/queue/rank?user_id=230